name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 12 * * 1-5"

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: |
        cd Frontend-Tests-Swag-Labs
        mvn test
